### ISSUE TITLE
[Request] Agent auto-config for harvester

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-operator#1057]
### Describe the feature

Currently the agent autoconfiguration only supports setting the harvester template, but no other harvester parameters. This only allows for on-stop uploads of recordings, but it would be nice to support periodic pushes as well.

**Comment by andrewazores** [comment]
Maybe this is not really needed in the end.

```yaml
spec:
  template:
    metadata:
      labels:
        cryostat.io/name: cryostat
        cryostat.io/namespace: cryostat
        cryostat.io/harvester-template: default
    spec:
      containers:
        - name: quarkus-test
          env:
            - name: CRYOSTAT_AGENT_HARVESTER_PERIOD_MS
              value: '30000'
            - name: CRYOSTAT_AGENT_HARVESTER_MAX_FILES
              value: '3'
```

This kind of Deployment snippet can already be applied, which uses the operator's Autoconfig to set up the Agent, but also contains additional manually-specified environment variables that the Agent will pick up and use to configure the Harvester further. It doesn't look as clean and tidy as having it all configured in one place (ie. the Pod labels), but it's functional and generally understandable. Adding full support for all Agent configurations to the autoconfiguration labels means more effort and maintenance in making sure any new Agent configuration parameters get mirrored as autoconfiguration labels.
