### ISSUE TITLE
Web UI WebSocket Error

### ISSUE THREAD

**Issue by misastovicek** [cryostatio/cryostat-operator#293]
Deployment to Azure Kubernetes Service as well as to Docker Desktop Kubernetes results in inability to login and a lot of WebSocker Error messages in the UI.

![websocket-error](https://user-images.githubusercontent.com/32091366/140887143-268e828b-40ed-4e85-bc55-9bf43d3eae15.png)

Docker Desktop Kubernetes version: `v1.19.7`
AKS version: `v1.20.5`

**Steps to reproduce:**

* Create namespace: `kubectl create namespace cryostat-operator-system`
* Deploy Operator: `kubectl apply -k 'github.com/cryostatio/cryostat-operator//config/default?ref=v2.0.0'`
* Deploy Cryostat:
```bash
cat <<EOF | kubectl apply -n cryostat-operator-system -f -
apiVersion: operator.cryostat.io/v1beta1
kind: Cryostat
metadata:
  name: cryostat-test
spec:
  minimal: false
  enableCertManager: false
EOF
```
* Port-forward to cryostat pod: `kubectl port-forward -n cryostat-operator-system pod/cryostat-test-9cb696549-zdkp7 8181 9090 3000`

I can see the same issue with Ingress configured on AKS - the following configuration:

```yaml
apiVersion: operator.cryostat.io/v1beta1
kind: Cryostat
metadata:
  name: cryostat-test
spec:
  minimal: false
  enableCertManager: false
  networkOptions:
    coreConfig:
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
        nginx.org/websocket-services: cryostat-test
      ingressSpec:
        rules:
        - host: cryostat.my-private-domain.azure
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: cryostat-test
                  port:
                    number: 8181
    commandConfig:
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
        nginx.org/websocket-services: cryostat-command
      ingressSpec:
        rules:
        - host: cryostat-command.my-private-domain.azure
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: cryostat-command
                  port:
                    number: 9090
    grafanaConfig:
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
        nginx.org/websocket-services: cryostat-grafana
      ingressSpec:
        rules:
        - host: cryostat-grafana.my-private-domain.azure
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: cryostat-grafana
                  port:
                    number: 3000
```

Also the specified annotations are not applied to the Ingress resources for some reason.

**Expected results:**

I should be able to successfully login with the credentials from Kubernetes Secrets resource.
