### ISSUE TITLE
Service Options and Network Options configuration

### ISSUE THREAD

**Issue by varun6121990** [cryostatio/cryostat-operator#354]
Hi Team,

We are just in the implementation phase of bringing in Cryostat in to our Kube cluster. We are using AWS EKS.

**Service options**

As per the documentation of cryostat-operator, we are  unable to expose core Cryostat application, Grafana, and cryostat-reports as service. The schema definition of cryostats.operator.cryostat.io does not have Service options itself. Attached the schema file for your reference. Please let us know how to expose these 3 as services.
[schema.txt](https://github.com/cryostatio/cryostat-operator/files/8315521/schema.txt)

**Network Options**

We are trying to use istio-ingress in ingress specification. But we are not able to get the pods in our namespace after applying the below yaml, only we could able to see these components coming as load balancer.

```
---
apiVersion: operator.cryostat.io/v1beta1
kind: Cryostat
metadata:
  name: cryostat-sample
spec:
  trustedCertSecrets: []
  enableCertManager: false
  minimal: false
  networkOptions:
    coreConfig:
      annotations:
        kubernetes.io/ingress.class: istio
        name: ingress
      ingressSpec:
          ingressClassName: kubernetes.io/ingress.class
          rules:
          -     host: testing.cryostat
                http:
                    paths:
                    -     backend:
                              service:
                                  name: cryostat-sample
                                  port:
                                      number: 443
                          path: /
                          pathType: Prefix
```

**Output:** kubectl get svc -n dev
Name                                  Type                     Port
cryostat-sample                 LoadBalancer     8181:30629/TCP,9091:30040/TCP   26m
cryostat-sample-grafana         LoadBalancer     3000:32348/TCP                  26m

Please help us on the above issues.
