### ISSUE TITLE
Cryostat Operator on Openshift on AWS fail to create an instance 

### ISSUE THREAD

**Issue by mcombi** [cryostatio/cryostat-operator#515]
On Openshift 4.11.8, running on AWS, i can't deploy an instance of cryostat with cryostat operator version 2.2.1. 
With the following yaml (which is the default one basically): 

```
apiVersion: operator.cryostat.io/v1beta1
kind: Cryostat
metadata:
  finalizers:
    - operator.cryostat.io/cryostat.finalizer
spec:
  enableCertManager: true
  minimal: false
  reportOptions:
    resources: {}
  storageOptions:
    emptyDir:
      enabled: true
```
I always get this error: 
(combined from similar events): Error creating: Pod "cryostat-sample2-7ccf79d9f-j8rvf" is invalid: spec.containers[1].resources.requests: Invalid value: "1": must be less than or equal to cpu limit
