### ISSUE TITLE
[Task] Lower Grafana default resource requests

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#564]
Our default resource requests for Grafana seem a bit steep and can cause scheduling issues on smaller clusters. If LimitRanges are set for a namespace, we can also run into issues like #515.

We currently use:
- 1 CPU
- 256 MiB Memory

See: https://github.com/cryostatio/cryostat-operator/blob/64e99afa82eb460846fdd61cbb3382db6fcbc312/docs/config.md#resource-requirements

I thought of trying out the [Grafana Operator](https://github.com/grafana-operator/grafana-operator) to see what it uses for default resource requests. When creating a Grafana instance with all default options, I got the following deployment:
```yaml
    - resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 256Mi
```

I think we could likely use the same requests. What do you think @tthvo?

Edit: Previously was using numbers from the init container.
