### ISSUE TITLE
[Bug] Operator controller manager Pod OOMKilled and crash looping

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-operator#716]
### Current Behavior

```
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 64Mi
....
lastState:
        terminated:
          exitCode: 137
          reason: OOMKilled
          startedAt: '2024-01-26T08:36:59Z'
          finishedAt: '2024-01-26T08:37:24Z'
```
[operator-pod.log](https://github.com/cryostatio/cryostat-operator/files/14065312/operator-pod.log)

Are the manager's resource limits hardcoded? Should this be increased by default and is there a way to make this configurable for the user?

https://github.com/cryostatio/cryostat-operator/blob/6ac7ec6aac49f3933b6314227e19b9d64a457b07/config/manager/manager.yaml#L59
