### ISSUE TITLE
[Bug] Allow to configure the custom routes domain for cryostat and grafana

### ISSUE THREAD

**Issue by ippul** [cryostatio/cryostat-operator#726]
### Current Behavior

When Cryostat is deployed using operator, the route host contains the openshift domain(`{instance-name}-{namespace-name}.{opc-instance-domain}`) and is not possible to customise it using via CR
Cryostat container stores the grafana routes in an enviroment variable named GRAFANA_DASHBOARD_EXT_URL so manually create the routes is not a suitable workaround

### Expected Behavior

Allow to customise the route domain using CR

### Steps To Reproduce

Create the custom resource
```
cat > my-app-cryostat.yaml << EOL
apiVersion: operator.cryostat.io/v1beta1 
kind: ClusterCryostat 
metadata: 
  name: my-app-cryostat
spec: 
  enableCertManager: true 
  installNamespace: cryostat-examples 
  minimal: false 
  reportOptions: 
    replicas: 1 
    resources: 
      limits: 
        cpu: '1' 
        memory: 1Gi 
      requests: 
        cpu: 500m 
        memory: 512Mi 
  resources: 
    coreResources: 
      limits: 
        cpu: '1' 
        memory: 2Gi 
      requests: 
        cpu: 500m 
        memory: 1Gi 
    dataSourceResources: 
      limits: 
        cpu: 500m 
        memory: 256Mi 
      requests: 
        memory: 256Mi 
    grafanaResources: 
      limits: 
        cpu: 500m 
        memory: 256Mi 
      requests: 
        memory: 256Mi 
  storageOptions: 
    pvc: 
      spec:
        resources: {} 
  targetDiscoveryOptions: 
    builtInDiscoveryDisabled: true 
EOL    
```

Apply the custom resource
`oc apply -f my-app-cryostat.yaml`

Verify the routes are in the format `{instance-name}-{namespace-name}.{opc-instance-domain}`
`oc get routes`

Check that the Cryostat container define an environment variable named "GRAFANA_DASHBOARD_EXT_URL" and value the route of the grafana instance

### Environment

```Markdown
- OS: 
- Environment: 
- Version:
```
