### ISSUE TITLE
[Bug] Fail to install Cryostat if using custom secret for database

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-operator#826]
### Current Behavior

Using an existing `db-secret` with Cryostat:

```yaml
apiVersion: operator.cryostat.io/v1beta2
kind: Cryostat
metadata:
  name: cryostat-sample
spec:
  enableCertManager: true
  trustedCertSecrets: []
  eventTemplates: []
  storageOptions:
    pvc:
      labels: {}
      annotations: {}
      spec: {}
  reportOptions:
    replicas: 0
  databaseOptions:
    secretName: db-secret

```

The deployment failed to roll out with below events;

```
  Normal   Pulled          3m21s                  kubelet            Successfully pulled image "quay.io/cryostat/cryostat-db:latest" in 1.478627454s (1.478634923s including waiting)
  Warning  Failed          3m21s                  kubelet            Error: secret "cryostat-sample-db" not found
```

It seems like the operator is still configuring the cryostat deployment with default generated secret (which should not be available).

### Expected Behavior

The deployment should use the custom secret for env vars.

### Steps To Reproduce

This affects cryostat `3.0`. On branch `cryostat3`, `make deploy_bundle` and apply the above cryostat YAML.

### Environment

```Markdown
- OS: Fedora 40
- CRC version: 2.26.0+233df0
- OpenShift version: 4.13.9
```

### Anything else?

https://github.com/cryostatio/cryostat-operator/blob/b300689a645e3741ccd5468e09acf20b5b9fb4d2/internal/controllers/common/resource_definitions/resource_definitions.go#L1418
