### ISSUE TITLE
[Bug] Cannot start out of the box on non-openshift cluster

### ISSUE THREAD

**Issue by grzesuav** [cryostatio/cryostat-operator#981]
### Current Behavior

Deployed operator with manifest
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      argocd-compute_cryostat-operator-staging:apps/Deployment:compute-platform-observability/cryostat-operator-controller
    deployment.kubernetes.io/revision: '1'
  labels:
    app.kubernetes.io/name: cryostat-operator
    control-plane: controller-manager
  name: cryostat-operator-controller
  namespace: compute-platform-observability

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: cryostat-operator
      control-plane: controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: cryostat-operator
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - '--leader-elect'
          command:
            - /manager
          env:
            - name: RELATED_IMAGE_OAUTH2_PROXY
              value: quay.io/oauth2-proxy/oauth2-proxy:latest
            - name: RELATED_IMAGE_OPENSHIFT_OAUTH_PROXY
              value: quay.io/cryostat/openshift-oauth-proxy:3.0.1
            - name: RELATED_IMAGE_CORE
              value: quay.io/cryostat/cryostat:3.0.1
            - name: RELATED_IMAGE_DATASOURCE
              value: quay.io/cryostat/jfr-datasource:3.0.1
            - name: RELATED_IMAGE_GRAFANA
              value: quay.io/cryostat/cryostat-grafana-dashboard:3.0.1
            - name: RELATED_IMAGE_REPORTS
              value: quay.io/cryostat/cryostat-reports:3.0.1
            - name: RELATED_IMAGE_STORAGE
              value: quay.io/cryostat/cryostat-storage:3.0.1
            - name: RELATED_IMAGE_DATABASE
              value: quay.io/cryostat/cryostat-db:3.0.1
            - name: WATCH_NAMESPACE
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: quay.io/cryostat/cryostat-operator:3.0.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: '1'
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: cryostat-operator-service-account
      serviceAccountName: cryostat-operator-service-account
      terminationGracePeriodSeconds: 10
status:
  conditions:
    - lastTransitionTime: '2024-12-06T11:26:05Z'
      lastUpdateTime: '2024-12-06T11:26:05Z'
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: 'False'
      type: Available
    - lastTransitionTime: '2024-12-06T11:26:05Z'
      lastUpdateTime: '2024-12-06T11:26:05Z'
      message: ReplicaSet "cryostat-operator-controller-5d7897c867" is progressing.
      reason: ReplicaSetUpdated
      status: 'True'
      type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1

```

and it is crash looping with
```
2024-12-06T11:28:25Z	ERROR	setup	could not determine whether manager is running on OpenShift	{"error": "Get \"https://10.188.64.1:443/apis/route.openshift.io/v1?timeout=32s\": EOF"}
main.main
	/workspace/internal/main.go:145
runtime.main
	/usr/local/go/src/runtime/proc.go:271
```

### Expected Behavior

Operator is runing

### Environment

```Markdown
- OS: 
- Environment: 
- Version:
```
